### ISSUE TITLE
Change the way lodash is being imported

### ISSUE THREAD

**Issue by bradbirnbaum** [bentatum/better-react-spinkit#11]
If you use `better-react-spinkit` in a project that already uses `lodash` we end up with duplicate imports of several lodash methods causing bundle bloat.

**Comment by bentatum** [comment]
I removed the individual lodash dependencies in favor of lodash being a peerDependency in the latest release. Hopefully that helps. Thanks.

**Comment by Reaverart** [comment]
@bentatum I'd like to ask to revert it. Not all projects relies on `lodash 4.x` our project uses `2.x` version and we cant update to latest spinkit version because it imports specific to `4.x` methods. Or maybe list needed methods in peer dependencies explicitly https://www.npmjs.com/browse/keyword/lodash-modularized
